version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "16"

  jobs:
    post_install:
      - npm ci
      - npm install -g jsdoc

sphinx:
  configuration: doc/conf.py

python:
   install:
   - requirements: doc/requirements.txt